//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpidaExampleAngularEF.Domain.Delete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ShipCountry { get; set; }
        public string ShipCity { get; set; }
        public string ShipZip { get; set; }
        public string ShipAddress { get; set; }
        public Nullable<float> Total { get; set; }
        public Nullable<int> Client_Id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}
